# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
