# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160824_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Processed', 'Processed'), ('Shipped', 'Shipped')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('xs', 'xs'), ('small', 'small'), ('med', 'med'), ('large', 'large'), ('xl', 'xl')], max_length=10),
        ),
    ]
